name: build-baseimage

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'manual build and publish'
  schedule:
    - cron: '0 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: vergilgao
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        file: ./build-stage/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/vergilgao/mdc-buildimage:dev
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}    
