name: nightly-build

on: 
  workflow_dispatch:
    inputs:
      build:
        description: '构建并上传夜间镜像'
  schedule:
    - cron: 0 0 * * 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up build args
      run: |
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: vergilgao
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: vergilgao
        password: ${{ secrets.GHCR_TOKEN }}

    - name: enable nightly command in dockerfile 
      run: |
        sed -i 's/#nightly //' Dockerfile

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          vergilgao/mdc:nightly
          ghcr.io/vergilgao/mdc:nightly
        build-args: |
          MDC_VERSION=master
          VERSION=nightly
          BUILD_DATE=${{ env.BUILD_DATE }}
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}    
