name: publish

on: 
  release:
    tags:
      - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Get avdc version
          run: |
            echo "AVDC_VERSION=$(cat VERSION)" >> $GITHUB_ENV
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
          if: success()
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          if: success()
        
        - name: Login to DockerHub
          uses: docker/login-action@v1
          if: success()
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          if: success()
          with:
            context: .
            file: Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            build-args: |
              AVDC_VERSION=${{ env.AVDC_VERSION }}
              BUILD_DATE=$(date +"%Y-%m-%d")
            tags: |
              vergilgao/avdc:${{ env.AVDC_VERSION }}
              vergilgao/avdc:latest
