name: test

on: 
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - ".github/workflows/sync-readme.yml"
      - ".github/workflows/release.yml"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "*.md"
      - ".github/workflows/sync-readme.yml"
      - ".github/workflows/release.yml"
      - "LICENSE"
  workflow_dispatch:
    inputs:
      start_test:
        description: '构建测试镜像'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get mdc version
      run: |
        echo "MDC_VERSION=$(cat VERSION)" >> $GITHUB_ENV
    
    - name: Create Test User and test files
      run: |
        sudo groupadd -g 1024 mdc
        sudo useradd -u 1024 mdc -g mdc
        mkdir test
        dd if=/dev/zero of="./test/MIFD-046.mp4" bs=250MB count=1
        dd if=/dev/zero of="./test/SVDVD-471.mp4.mp4" bs=250MB count=1
        sudo chown -R 99:100 test
        ls -al test

    - name: Build the test image
      run: |
        docker build -t vergilgao/mdc:test \
          --build-arg MDC_VERSION=${{ env.MDC_VERSION }} \
          --build-arg BUILD_DATE=$(date +"%Y-%m-%d") \
          .  

    - name: Run the Test
      if: success()
      run: |
        docker run \
          -e SUCCESS_OUTPUT="test_output" \
          -e DEBUG=1 \
          -e PUID=1024 \
          -e PGID=1024 \
          -v ${PWD}/test:/data \
          vergilgao/mdc:test
        find . -name MIFD-046.mp4
        find . -name SVDVD-471.mp4
        ls -al test
